# Generated by Django 4.0.3 on 2022-03-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMovie',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('movieName', models.CharField(max_length=100)),
                ('movieType', models.CharField(max_length=20)),
                ('movieReleasedate', models.DateField()),
                ('movieDescription', models.TextField()),
                ('movieImage', models.ImageField(default='No-Image.png', upload_to='Bollywoodimages/')),
                ('movieLink', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HMovie',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('movieName', models.CharField(max_length=100)),
                ('movieType', models.CharField(max_length=20)),
                ('movieReleasedate', models.DateField()),
                ('movieDescription', models.TextField()),
                ('movieImage', models.ImageField(default='No-Image.png', upload_to='Hollywoodimages/')),
                ('movieLink', models.CharField(max_length=250)),
            ],
        ),
    ]
